version: '3'

services:
  
  nginx_dev:
    build: nginx
    ports:
      - "80:8000"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    volumes:
      - ./Frontend:/src